### ISSUE TITLE
Component: Table

### ISSUE THREAD

**Issue by jonnystening** [WestpacGEL/GEL#44]
## Features
- [x] Bordered prop
- [x] Responsive prop
- [x] Bordered
- [x] Bordered & striped
- [x] Responsive
- [x] Examples
- [ ] Jest tests
- [ ] Cypress tests
- [x] Docs

## To discuss
- [ ] Table component currently only provides the parent wrapping. Row and cell (children) elements are composed with standard html elements. Are there any benefits in abstracting these standard html elements into React components?

- [ ] Responsive table (wrapper) element enabled via prop. Maybe this should be the default? `noResponsive` prop to disable?

- [ ] Table wrapper class `table-responsive` doesn't feel right. Used by Panel component styling; responsive table styling reset when placed inside Panel.

- [ ] `.table-highlight` class doesn't feel very react-esque

- [ ] TableWrapper approach? Should it be in the Table.js file or moved to a styled.js or TableWrapper.js (note: it's not exported)
- [ ] Table can be composed within Panel. A `.table-responsive` className is rendered in case Panel composes a responsive Table (as it requires some style tweaks). Is there another way, without the className?
- [ ] How else can we do the `.table-highlight` on cells/rows?
- [ ] Do we need to check proptypes for a wrapper component that's not exported?

## Feedback from Kate's review
- **Table/examples** -  Wrong styling for _Table caption text_, it's too light 
_JPS: need to discuss, Dom has implemented a solution to handle system fonts not having all weights_
_JPS: This restriction has now been removed_

**Comment by jaortiz** [comment]
Need to further discuss whether we should create a react component for table elements. Currently only using react for the <table> tag and targeting specific cell highlighting via classNames. Not sure if this is the correct way to do this.

**Comment by jonnystening** [comment]
> Need to further discuss whether we should create a react component for table elements. Currently only using react for the
> 
> tag and targeting specific cell highlighting via classNames. Not sure if this is the correct way to do this.

All Table sub-elements (`<tr>`,`<th>`, `<td>` etc) are now in React
