### ISSUE TITLE
Unable to pass `state` to component rendered as Button

### ISSUE THREAD

**Issue by wojtekmaj** [WestpacGEL/GEL#771]
**Describe the bug**
When creating a button that uses `Link` as `tag`, `state` prop gets excluded. All other props seem to be passing just fine.

**To Reproduce**

```js
import { Link } from 'react-router-dom';
import { Button } from '@westpac/button';

export default function LinkButton({ replace, state, to }) {
  return (
    <Button tag={Link} replace={replace} state={state} to={to} />
  );
}
```

**Expected behavior**
`Link` to receive all props necessary.

**Comment by dominikwilkowski** [comment]
I can't reproduce this.
We literally have a test case for the very same thing you showed here and it works: https://github.com/WestpacGEL/GEL/blob/master/components/button/examples/10-button-tags.js#L43

which of the props aren't being passed in?

**Comment by wojtekmaj** [comment]
Thanks for this workaround! That should work for me. Just a note that this came up when I tried integrating GEL with Link from React-Router 6 which is currently in baking and will be probably **widely** used once released. You will probably want to make it easier for the teams that will be adopting it.

**Comment by dominikwilkowski** [comment]
Yeah maybe we rename the `state` internal prop to something like `__internal_state` or something...
