### ISSUE TITLE
Wrong package names in documentation

### ISSUE THREAD

**Issue by wojtekmaj** [WestpacGEL/GEL#781]
**Describe the bug**

On this page:
https://gel.westpacgroup.com.au/design-system/components/radios?b=WBC

we see that the instructions to install the package are

```
npm install @westpac/form_check
```

where they should be

```
npm install @westpac/form-check
```

**Comment by wojtekmaj** [comment]
Oh, and "View Changes" link is also dead.

**Comment by wojtekmaj** [comment]
Same applies to https://gel.westpacgroup.com.au/design-system/components/button-dropdowns?b=WBC

**Comment by jonnystening** [comment]
Thanks been on our backlog for a little while

https://github.com/WestpacGEL/GEL/pull/805
