### ISSUE TITLE
Installation instructions are broken

### ISSUE THREAD

**Issue by wojtekmaj** [WestpacGEL/GEL#796]
**Describe the bug**

On https://westpacgel.netlify.app/alert, all installation instructions are missing package name.

**To Reproduce**

1. Visit the page

**Expected behavior**

Installation instructions to be correct

**Screenshots**

![image](https://user-images.githubusercontent.com/5426427/131084877-37167a49-55b5-4314-aa39-5c8ab513ad9e.png)

**Comment by jonnystening** [comment]
Thanks for noticing this

https://github.com/WestpacGEL/GEL/pull/805
