### ISSUE TITLE
Collapsible component missing Trigger overrides in propTypes

### ISSUE THREAD

**Issue by wojtekmaj** [WestpacGEL/GEL#799]
**Describe the bug**

Collapsible overrides defined in propTypes are missing Trigger overrides.

**To Reproduce**

https://github.com/WestpacGEL/GEL/blob/74dc81090cec0bfbd61a334b5787cc41a2b67ae1/components/collapsible/src/Collapsible.js#L165-L176

**Comment by jonnystening** [comment]
Thanks for picking this up

https://github.com/WestpacGEL/GEL/pull/805
