### ISSUE TITLE
Bolt new with multi-word component name

### ISSUE THREAD

**Issue by jonnystening** [WestpacGEL/GEL#80]
When `bolt new`ing a multi-word component name the task needs to remove the dash and pascal case each of the words when it replaces the template’s `_COMPONENT_NAME_` placeholder and sets a file name.

e.g. `button-group` ==> `ButtonGroup` etc

**Comment by jaortiz** [comment]
PR raised

**Comment by jonnystening** [comment]
Still having issues...

Just did a `bolt new form-pod` and got this in the README.md...

```# @westpac/formPod```

Should me...

```# @westpac/form-pod```

Also in docs.mdx and package.json

`_COMPONENT_KEY_` needs to be replaced with the original CLI passed name (ie. in kebab case)

will raise a PR

**Comment by jonnystening** [comment]
PR raised https://github.com/WestpacGEL/GEL/pull/92
