### ISSUE TITLE
Allow React nodes as Tabcordion tab titles

### ISSUE THREAD

**Issue by wojtekmaj** [WestpacGEL/GEL#801]
**Is your feature request related to a problem? Please describe.**

I would like to include additional formatting to Tabcordion tab titles, like so:

```js
      <Tabcordion>
        <Tab text={(
          <>
            Tab
            {' '}
            <strong>one</strong>
          </>
        )}
        >
          Tab 1
        </Tab>
        <Tab text="Tab 2">
          Tab 2
        </Tab>
      </Tabcordion>
```

This, however, causes propTypes error, not providing any benefit I could think of.

**Describe the solution you'd like**

Allow React nodes as Tabcordion tab titles

**Describe alternatives you've considered**

Overwriting propTypes, but that's just ridiculous and unsafe.

**Comment by jonnystening** [comment]
Will be adding this request to the roadmap, changes likely made and published this week

It's unlikely we'd ever recommend anything other than text being used within a tab/accordion toggle (ie. no icons, images etc), but can see a use case here to allow basic type styling (ie. bold).
