### ISSUE TITLE
Unable to override Tr hover color in Table

### ISSUE THREAD

**Issue by wojtekmaj** [WestpacGEL/GEL#802]
**Describe the bug**

Due to how Table styles are built, it's impossible (or at least very hard) to overwrite Tr hover color.

**To Reproduce**

Here's what I tried:

```js
const overrides = {
  Tr: {
    styles: (styles) => ({
      ...styles,
      ':hover': {
        backgroundColor: 'red',
      },
    }),
  },
};
```

and here's what I got:

![image](https://user-images.githubusercontent.com/5426427/131832617-e8fc4e72-7e78-45b0-9283-c4ceff2fe08f.png)

**Expected behavior**

Tr hover color changed to red.

**Screenshots**

**Comment by jaortiz** [comment]
Due to the way we had to architect Table to work with another legacy system, the Tr hover color is currently part of the Table styles.  

```
const overrides = {
Table: {
    styles: (styles) => ({
        ...styles,
        'tbody > tr': {
            transition: 'background 0.2s ease',
            ':hover': {
                backgroundColor: 'red',
            },
        },
    }),
},
}
```

**Comment by wojtekmaj** [comment]
That works! Thanks so much @jaortiz!
